#version: '3'
services:
  conwaygui:
#    image: docker.io/natbodocker/conwayguialone:2.0
    image: conwayguialone:2.0
    ports:
      - "7110:7110"
    environment:
      - MQTTBROKER_URL=tcp://192.168.1.132:1883		
#      - HOST_IP=conwaygui		
#       - HOST_IP=192.168.1.132
      - HOST_IP=192.168.1.132
#      - HOST_IP=130.136.113.239
#    network_mode: "host"
    networks:
      - conwaylifenet

networks:
    conwaylifenet:
        external: true


## docker-compose -f conwayguialone.yaml -p conwayguialone up   

## netstat -ano 
## Wireshark